# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1117, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_gaussian = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gaussian.setGeometry(QtCore.QRect(14, 537, 133, 20))
        self.lineEdit_gaussian.setObjectName("lineEdit_gaussian")
        self.lineEdit_lorentzian = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lorentzian.setGeometry(QtCore.QRect(153, 537, 133, 20))
        self.lineEdit_lorentzian.setObjectName("lineEdit_lorentzian")
        self.lineEdit_center = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_center.setGeometry(QtCore.QRect(292, 537, 133, 20))
        self.lineEdit_center.setObjectName("lineEdit_center")
        self.lineEdit_height = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_height.setGeometry(QtCore.QRect(431, 537, 133, 20))
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(14, 517, 43, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(153, 517, 56, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(292, 517, 33, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(431, 517, 31, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton_fit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fit.setGeometry(QtCore.QRect(570, 536, 75, 23))
        self.pushButton_fit.setObjectName("pushButton_fit")
        self.canvas = QtWidgets.QWidget(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(14, 11, 631, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy)
        self.canvas.setMinimumSize(QtCore.QSize(500, 500))
        self.canvas.setObjectName("canvas")
        self.lineEdit_address = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_address.setGeometry(QtCore.QRect(650, 30, 380, 20))
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.pushButton_browse = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browse.setGeometry(QtCore.QRect(1030, 30, 75, 20))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.checkBox_constant_background = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_constant_background.setGeometry(QtCore.QRect(680, 470, 131, 17))
        self.checkBox_constant_background.setObjectName("checkBox_constant_background")
        self.checkBox_linear_background = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_linear_background.setGeometry(QtCore.QRect(680, 490, 121, 17))
        self.checkBox_linear_background.setObjectName("checkBox_linear_background")
        self.checkBox_step_background = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_step_background.setGeometry(QtCore.QRect(680, 530, 121, 17))
        self.checkBox_step_background.setObjectName("checkBox_step_background")
        self.checkBox_polynomial_background = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_polynomial_background.setGeometry(QtCore.QRect(680, 510, 131, 17))
        self.checkBox_polynomial_background.setObjectName("checkBox_polynomial_background")
        self.comboBox_peak = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_peak.setGeometry(QtCore.QRect(680, 440, 131, 22))
        self.comboBox_peak.setObjectName("comboBox_peak")
        self.comboBox_peak.addItem("")
        self.comboBox_peak.addItem("")
        self.comboBox_peak.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 420, 71, 16))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_gaussian.setText(_translate("MainWindow", "1"))
        self.lineEdit_lorentzian.setText(_translate("MainWindow", "1"))
        self.lineEdit_center.setText(_translate("MainWindow", "0"))
        self.lineEdit_height.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "Gaussian"))
        self.label_2.setText(_translate("MainWindow", "Lorenztian"))
        self.label_3.setText(_translate("MainWindow", "Center"))
        self.label_4.setText(_translate("MainWindow", "Height"))
        self.pushButton_fit.setText(_translate("MainWindow", "Fit"))
        self.lineEdit_address.setText(_translate("MainWindow", "C:\\"))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse"))
        self.checkBox_constant_background.setText(_translate("MainWindow", "Constant Background"))
        self.checkBox_linear_background.setText(_translate("MainWindow", "Linear Background"))
        self.checkBox_step_background.setText(_translate("MainWindow", "Step Background"))
        self.checkBox_polynomial_background.setText(_translate("MainWindow", "Polynomial Background"))
        self.comboBox_peak.setItemText(0, _translate("MainWindow", "Voigt"))
        self.comboBox_peak.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.comboBox_peak.setItemText(2, _translate("MainWindow", "Lorentzian"))
        self.label_5.setText(_translate("MainWindow", "Peak Type"))

