# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectraanalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpectraAnalyzer(object):
    def setupUi(self, SpectraAnalyzer):
        SpectraAnalyzer.setObjectName("SpectraAnalyzer")
        SpectraAnalyzer.resize(1297, 646)
        self.centralWidget = QtWidgets.QWidget(SpectraAnalyzer)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Project = QtWidgets.QWidget()
        self.tab_Project.setObjectName("tab_Project")
        self.label_project_sample = QtWidgets.QLabel(self.tab_Project)
        self.label_project_sample.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_project_sample.setObjectName("label_project_sample")
        self.lineEdit_project_Sample_3 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_3.setGeometry(QtCore.QRect(14, 104, 133, 20))
        self.lineEdit_project_Sample_3.setObjectName("lineEdit_project_Sample_3")
        self.pushButton_browse_7 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_7.setGeometry(QtCore.QRect(150, 232, 75, 23))
        self.pushButton_browse_7.setObjectName("pushButton_browse_7")
        self.lineEdit_project_Sample_7 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_7.setGeometry(QtCore.QRect(14, 232, 133, 20))
        self.lineEdit_project_Sample_7.setObjectName("lineEdit_project_Sample_7")
        self.lineEdit_project_Sample_5 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_5.setGeometry(QtCore.QRect(14, 168, 133, 20))
        self.lineEdit_project_Sample_5.setObjectName("lineEdit_project_Sample_5")
        self.pushButton_browse_6 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_6.setGeometry(QtCore.QRect(150, 200, 75, 23))
        self.pushButton_browse_6.setObjectName("pushButton_browse_6")
        self.lineEdit_project_Sample_8 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_8.setGeometry(QtCore.QRect(14, 264, 133, 20))
        self.lineEdit_project_Sample_8.setObjectName("lineEdit_project_Sample_8")
        self.pushButton_browse_3 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_3.setGeometry(QtCore.QRect(150, 104, 75, 23))
        self.pushButton_browse_3.setObjectName("pushButton_browse_3")
        self.lineEdit_project_Sample_4 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_4.setGeometry(QtCore.QRect(14, 136, 133, 20))
        self.lineEdit_project_Sample_4.setObjectName("lineEdit_project_Sample_4")
        self.lineEdit_project_Sample_2 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_2.setGeometry(QtCore.QRect(14, 72, 133, 20))
        self.lineEdit_project_Sample_2.setObjectName("lineEdit_project_Sample_2")
        self.pushButton_browse_4 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_4.setGeometry(QtCore.QRect(150, 136, 75, 23))
        self.pushButton_browse_4.setObjectName("pushButton_browse_4")
        self.lineEdit_project_Sample_6 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_6.setGeometry(QtCore.QRect(14, 200, 133, 20))
        self.lineEdit_project_Sample_6.setObjectName("lineEdit_project_Sample_6")
        self.pushButton_browse_5 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_5.setGeometry(QtCore.QRect(150, 168, 75, 23))
        self.pushButton_browse_5.setObjectName("pushButton_browse_5")
        self.lineEdit_project_Sample_1 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_1.setGeometry(QtCore.QRect(14, 40, 133, 20))
        self.lineEdit_project_Sample_1.setObjectName("lineEdit_project_Sample_1")
        self.pushButton_browse_2 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_2.setGeometry(QtCore.QRect(150, 72, 75, 23))
        self.pushButton_browse_2.setObjectName("pushButton_browse_2")
        self.pushButton_browse_1 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_1.setGeometry(QtCore.QRect(150, 40, 75, 23))
        self.pushButton_browse_1.setObjectName("pushButton_browse_1")
        self.pushButton_browse_10 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_10.setGeometry(QtCore.QRect(150, 328, 75, 23))
        self.pushButton_browse_10.setObjectName("pushButton_browse_10")
        self.pushButton_browse_11 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_11.setGeometry(QtCore.QRect(150, 360, 75, 23))
        self.pushButton_browse_11.setObjectName("pushButton_browse_11")
        self.pushButton_browse_12 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_12.setGeometry(QtCore.QRect(150, 392, 75, 23))
        self.pushButton_browse_12.setObjectName("pushButton_browse_12")
        self.lineEdit_project_Sample_9 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_9.setGeometry(QtCore.QRect(14, 296, 133, 20))
        self.lineEdit_project_Sample_9.setObjectName("lineEdit_project_Sample_9")
        self.lineEdit_project_Sample_13 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_13.setGeometry(QtCore.QRect(14, 424, 133, 20))
        self.lineEdit_project_Sample_13.setObjectName("lineEdit_project_Sample_13")
        self.pushButton_browse_13 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_13.setGeometry(QtCore.QRect(150, 424, 75, 23))
        self.pushButton_browse_13.setObjectName("pushButton_browse_13")
        self.lineEdit_project_Sample_11 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_11.setGeometry(QtCore.QRect(14, 360, 133, 20))
        self.lineEdit_project_Sample_11.setObjectName("lineEdit_project_Sample_11")
        self.pushButton_browse_9 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_9.setGeometry(QtCore.QRect(150, 296, 75, 23))
        self.pushButton_browse_9.setObjectName("pushButton_browse_9")
        self.lineEdit_project_Sample_12 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_12.setGeometry(QtCore.QRect(14, 392, 133, 20))
        self.lineEdit_project_Sample_12.setObjectName("lineEdit_project_Sample_12")
        self.lineEdit_project_Sample_10 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_10.setGeometry(QtCore.QRect(14, 328, 133, 20))
        self.lineEdit_project_Sample_10.setObjectName("lineEdit_project_Sample_10")
        self.pushButton_browse_8 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_8.setGeometry(QtCore.QRect(150, 264, 75, 23))
        self.pushButton_browse_8.setObjectName("pushButton_browse_8")
        self.lineEdit_project_Sample_14 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_14.setGeometry(QtCore.QRect(14, 456, 133, 20))
        self.lineEdit_project_Sample_14.setObjectName("lineEdit_project_Sample_14")
        self.pushButton_browse_14 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_14.setGeometry(QtCore.QRect(150, 456, 75, 23))
        self.pushButton_browse_14.setObjectName("pushButton_browse_14")
        self.pushButton_browse_16 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_16.setGeometry(QtCore.QRect(150, 520, 75, 23))
        self.pushButton_browse_16.setObjectName("pushButton_browse_16")
        self.pushButton_browse_15 = QtWidgets.QPushButton(self.tab_Project)
        self.pushButton_browse_15.setGeometry(QtCore.QRect(150, 488, 75, 23))
        self.pushButton_browse_15.setObjectName("pushButton_browse_15")
        self.lineEdit_project_Sample_16 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_16.setGeometry(QtCore.QRect(14, 520, 133, 20))
        self.lineEdit_project_Sample_16.setObjectName("lineEdit_project_Sample_16")
        self.lineEdit_project_Sample_15 = QtWidgets.QLineEdit(self.tab_Project)
        self.lineEdit_project_Sample_15.setGeometry(QtCore.QRect(14, 488, 133, 20))
        self.lineEdit_project_Sample_15.setObjectName("lineEdit_project_Sample_15")
        self.label_project_sample.raise_()
        self.tabWidget.addTab(self.tab_Project, "")
        self.tab_Peaks = QtWidgets.QWidget()
        self.tab_Peaks.setObjectName("tab_Peaks")
        self.tabWidget.addTab(self.tab_Peaks, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        SpectraAnalyzer.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(SpectraAnalyzer)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1297, 21))
        self.menuBar.setObjectName("menuBar")
        SpectraAnalyzer.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(SpectraAnalyzer)
        self.mainToolBar.setObjectName("mainToolBar")
        SpectraAnalyzer.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(SpectraAnalyzer)
        self.statusBar.setObjectName("statusBar")
        SpectraAnalyzer.setStatusBar(self.statusBar)

        self.retranslateUi(SpectraAnalyzer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SpectraAnalyzer)

    def retranslateUi(self, SpectraAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        SpectraAnalyzer.setWindowTitle(_translate("SpectraAnalyzer", "SpectraAnalyzer"))
        self.label_project_sample.setText(_translate("SpectraAnalyzer", "Samples Folders"))
        self.pushButton_browse_7.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_6.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_3.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_4.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_5.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_2.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_1.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_10.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_11.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_12.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_13.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_9.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_8.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_14.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_16.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_15.setText(_translate("SpectraAnalyzer", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Project), _translate("SpectraAnalyzer", "Project"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Peaks), _translate("SpectraAnalyzer", "Peaks"))

