# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spectraanalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpectraAnalyzer(object):
    def setupUi(self, SpectraAnalyzer):
        SpectraAnalyzer.setObjectName("SpectraAnalyzer")
        SpectraAnalyzer.resize(1297, 646)
        self.centralWidget = QtWidgets.QWidget(SpectraAnalyzer)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Project = QtWidgets.QWidget()
        self.tab_Project.setObjectName("tab_Project")
        self.label_project_sample = QtWidgets.QLabel(self.tab_Project)
        self.label_project_sample.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_project_sample.setObjectName("label_project_sample")
        self.widget = QtWidgets.QWidget(self.tab_Project)
        self.widget.setGeometry(QtCore.QRect(13, 35, 401, 521))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_project_Sample_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_3.setObjectName("lineEdit_project_Sample_3")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_3, 2, 0, 1, 1)
        self.lineEdit_project_Sample_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_7.setObjectName("lineEdit_project_Sample_7")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_7, 6, 0, 1, 1)
        self.pushButton_browse_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_7.setObjectName("pushButton_browse_7")
        self.gridLayout_2.addWidget(self.pushButton_browse_7, 6, 1, 1, 1)
        self.lineEdit_project_Sample_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_5.setObjectName("lineEdit_project_Sample_5")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_5, 4, 0, 1, 1)
        self.lineEdit_project_Sample_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_8.setObjectName("lineEdit_project_Sample_8")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_8, 7, 0, 1, 1)
        self.pushButton_browse_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_6.setObjectName("pushButton_browse_6")
        self.gridLayout_2.addWidget(self.pushButton_browse_6, 5, 1, 1, 1)
        self.lineEdit_project_Sample_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_4.setObjectName("lineEdit_project_Sample_4")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_4, 3, 0, 1, 1)
        self.pushButton_browse_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_3.setObjectName("pushButton_browse_3")
        self.gridLayout_2.addWidget(self.pushButton_browse_3, 2, 1, 1, 1)
        self.lineEdit_project_Sample_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_2.setObjectName("lineEdit_project_Sample_2")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_2, 1, 0, 1, 1)
        self.pushButton_browse_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_4.setObjectName("pushButton_browse_4")
        self.gridLayout_2.addWidget(self.pushButton_browse_4, 3, 1, 1, 1)
        self.lineEdit_project_Sample_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_6.setObjectName("lineEdit_project_Sample_6")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_6, 5, 0, 1, 1)
        self.pushButton_browse_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_5.setObjectName("pushButton_browse_5")
        self.gridLayout_2.addWidget(self.pushButton_browse_5, 4, 1, 1, 1)
        self.lineEdit_project_Sample_1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_1.setObjectName("lineEdit_project_Sample_1")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_1, 0, 0, 1, 1)
        self.pushButton_browse_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_1.setObjectName("pushButton_browse_1")
        self.gridLayout_2.addWidget(self.pushButton_browse_1, 0, 1, 1, 1)
        self.pushButton_browse_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_2.setObjectName("pushButton_browse_2")
        self.gridLayout_2.addWidget(self.pushButton_browse_2, 1, 1, 1, 1)
        self.pushButton_browse_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_10.setObjectName("pushButton_browse_10")
        self.gridLayout_2.addWidget(self.pushButton_browse_10, 9, 1, 1, 1)
        self.pushButton_browse_12 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_12.setObjectName("pushButton_browse_12")
        self.gridLayout_2.addWidget(self.pushButton_browse_12, 11, 1, 1, 1)
        self.pushButton_browse_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_11.setObjectName("pushButton_browse_11")
        self.gridLayout_2.addWidget(self.pushButton_browse_11, 10, 1, 1, 1)
        self.lineEdit_project_Sample_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_9.setObjectName("lineEdit_project_Sample_9")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_9, 8, 0, 1, 1)
        self.lineEdit_project_Sample_13 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_13.setObjectName("lineEdit_project_Sample_13")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_13, 12, 0, 1, 1)
        self.pushButton_browse_13 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_13.setObjectName("pushButton_browse_13")
        self.gridLayout_2.addWidget(self.pushButton_browse_13, 12, 1, 1, 1)
        self.lineEdit_project_Sample_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_11.setObjectName("lineEdit_project_Sample_11")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_11, 10, 0, 1, 1)
        self.lineEdit_project_Sample_12 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_12.setObjectName("lineEdit_project_Sample_12")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_12, 11, 0, 1, 1)
        self.pushButton_browse_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_9.setObjectName("pushButton_browse_9")
        self.gridLayout_2.addWidget(self.pushButton_browse_9, 8, 1, 1, 1)
        self.pushButton_browse_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_8.setObjectName("pushButton_browse_8")
        self.gridLayout_2.addWidget(self.pushButton_browse_8, 7, 1, 1, 1)
        self.lineEdit_project_Sample_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_10.setObjectName("lineEdit_project_Sample_10")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_10, 9, 0, 1, 1)
        self.lineEdit_project_Sample_14 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_14.setObjectName("lineEdit_project_Sample_14")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_14, 13, 0, 1, 1)
        self.pushButton_browse_16 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_16.setObjectName("pushButton_browse_16")
        self.gridLayout_2.addWidget(self.pushButton_browse_16, 15, 1, 1, 1)
        self.pushButton_browse_14 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_14.setObjectName("pushButton_browse_14")
        self.gridLayout_2.addWidget(self.pushButton_browse_14, 13, 1, 1, 1)
        self.pushButton_browse_15 = QtWidgets.QPushButton(self.widget)
        self.pushButton_browse_15.setObjectName("pushButton_browse_15")
        self.gridLayout_2.addWidget(self.pushButton_browse_15, 14, 1, 1, 1)
        self.lineEdit_project_Sample_16 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_16.setObjectName("lineEdit_project_Sample_16")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_16, 15, 0, 1, 1)
        self.lineEdit_project_Sample_15 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_project_Sample_15.setObjectName("lineEdit_project_Sample_15")
        self.gridLayout_2.addWidget(self.lineEdit_project_Sample_15, 14, 0, 1, 1)
        self.lineEdit_project_Sample_1.raise_()
        self.label_project_sample.raise_()
        self.lineEdit_project_Sample_1.raise_()
        self.lineEdit_project_Sample_2.raise_()
        self.lineEdit_project_Sample_3.raise_()
        self.lineEdit_project_Sample_4.raise_()
        self.lineEdit_project_Sample_5.raise_()
        self.lineEdit_project_Sample_6.raise_()
        self.lineEdit_project_Sample_7.raise_()
        self.lineEdit_project_Sample_8.raise_()
        self.lineEdit_project_Sample_9.raise_()
        self.lineEdit_project_Sample_10.raise_()
        self.lineEdit_project_Sample_11.raise_()
        self.lineEdit_project_Sample_12.raise_()
        self.lineEdit_project_Sample_13.raise_()
        self.lineEdit_project_Sample_14.raise_()
        self.lineEdit_project_Sample_15.raise_()
        self.lineEdit_project_Sample_16.raise_()
        self.pushButton_browse_1.raise_()
        self.pushButton_browse_2.raise_()
        self.pushButton_browse_3.raise_()
        self.pushButton_browse_4.raise_()
        self.pushButton_browse_5.raise_()
        self.pushButton_browse_6.raise_()
        self.pushButton_browse_7.raise_()
        self.pushButton_browse_8.raise_()
        self.pushButton_browse_9.raise_()
        self.pushButton_browse_10.raise_()
        self.pushButton_browse_11.raise_()
        self.pushButton_browse_12.raise_()
        self.pushButton_browse_13.raise_()
        self.pushButton_browse_14.raise_()
        self.pushButton_browse_15.raise_()
        self.pushButton_browse_16.raise_()
        self.tabWidget.addTab(self.tab_Project, "")
        self.tab_Peaks = QtWidgets.QWidget()
        self.tab_Peaks.setObjectName("tab_Peaks")
        self.tabWidget.addTab(self.tab_Peaks, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        SpectraAnalyzer.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(SpectraAnalyzer)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1297, 21))
        self.menuBar.setObjectName("menuBar")
        SpectraAnalyzer.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(SpectraAnalyzer)
        self.mainToolBar.setObjectName("mainToolBar")
        SpectraAnalyzer.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(SpectraAnalyzer)
        self.statusBar.setObjectName("statusBar")
        SpectraAnalyzer.setStatusBar(self.statusBar)

        self.retranslateUi(SpectraAnalyzer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SpectraAnalyzer)

    def retranslateUi(self, SpectraAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        SpectraAnalyzer.setWindowTitle(_translate("SpectraAnalyzer", "SpectraAnalyzer"))
        self.label_project_sample.setText(_translate("SpectraAnalyzer", "Samples Folders"))
        self.pushButton_browse_7.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_6.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_3.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_4.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_5.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_1.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_2.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_10.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_12.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_11.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_13.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_9.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_8.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_16.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_14.setText(_translate("SpectraAnalyzer", "Browse"))
        self.pushButton_browse_15.setText(_translate("SpectraAnalyzer", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Project), _translate("SpectraAnalyzer", "Project"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Peaks), _translate("SpectraAnalyzer", "Peaks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpectraAnalyzer = QtWidgets.QMainWindow()
    ui = Ui_SpectraAnalyzer()
    ui.setupUi(SpectraAnalyzer)
    SpectraAnalyzer.show()
    sys.exit(app.exec_())

